//
// 
// THIS FILE HAS BEEN GENERATED. DO NOT MODIFY.
//

using System;
using System.Collections.Generic;
using byps;

namespace EloixClient.IndexServer.feed
{
	
	/// <summary>
	/// This class describes an entry in a document feed.
	/// </summary>
	/// <remarks>
	/// There are three kinds of entries/actions in general.
	/// First, an action can be a comment added manually by a user.
	/// Second, scripts or programs can insert actions e.g. to notify about a particular state.
	/// Third, actions are generated by the system e.g. when a new document version is created.
	/// In order to add an action to a feed, call {@link FeedService#checkinAction(de.elo.ix.client.ClientInfo, Action, ActionZ)}.
	/// User comments can have a parent action to support a two level hierarchy of entries.
	/// </remarks>
	public class Action : EloixClient.IndexServer.ValueClass, BSerializable
	{
	
		#region Constructors
		
		public Action() {
		}		
		
		public Action(String @guid, EloixClient.IndexServer.feed.EActionType @type, String @feedGuid, String @parentGuid, String @userGuid, int @userId, String @userName, String @createDateIso, String @updateDateIso, int @changeCounter, String @text, String @docVersionGuid, EloixClient.IndexServer.DocVersion @docVersion, String @workflowGuid, EloixClient.IndexServer.WFDiagram @workflow, String @TStamp, IList<EloixClient.IndexServer.feed.ActionHistory> @history, String @acl, EloixClient.IndexServer.AclItem[] @aclItems, String @TStampSync) {
			this.guidValue = @guid;
			this.typeValue = @type;
			this.feedGuidValue = @feedGuid;
			this.parentGuidValue = @parentGuid;
			this.userGuidValue = @userGuid;
			this.userIdValue = @userId;
			this.userNameValue = @userName;
			this.createDateIsoValue = @createDateIso;
			this.updateDateIsoValue = @updateDateIso;
			this.changeCounterValue = @changeCounter;
			this.textValue = @text;
			this.docVersionGuidValue = @docVersionGuid;
			this.docVersionValue = @docVersion;
			this.workflowGuidValue = @workflowGuid;
			this.workflowValue = @workflow;
			this.TStampValue = @TStamp;
			this.historyValue = @history;
			this.aclValue = @acl;
			this.aclItemsValue = @aclItems;
			this.TStampSyncValue = @TStampSync;
		}		
		
		public Action(Action rhs) : base(rhs)
		{
			this.guidValue = rhs.guidValue;
			this.typeValue = rhs.typeValue;
			this.feedGuidValue = rhs.feedGuidValue;
			this.parentGuidValue = rhs.parentGuidValue;
			this.userGuidValue = rhs.userGuidValue;
			this.userIdValue = rhs.userIdValue;
			this.userNameValue = rhs.userNameValue;
			this.createDateIsoValue = rhs.createDateIsoValue;
			this.updateDateIsoValue = rhs.updateDateIsoValue;
			this.changeCounterValue = rhs.changeCounterValue;
			this.textValue = rhs.textValue;
			this.docVersionGuidValue = rhs.docVersionGuidValue;
			this.docVersionValue = rhs.docVersionValue;
			this.workflowGuidValue = rhs.workflowGuidValue;
			this.workflowValue = rhs.workflowValue;
			this.TStampValue = rhs.TStampValue;
			this.historyValue = rhs.historyValue;
			this.aclValue = rhs.aclValue;
			this.aclItemsValue = rhs.aclItemsValue;
			this.TStampSyncValue = rhs.TStampSyncValue;
		}		
		
		#endregion
		
		#region Properties
		
		/// <summary>
		/// Action GUID.
		/// </summary>
		/// <remarks>
		/// Unique identifier.
		/// </remarks>
		public String guid
		{
			get
			{
				return guidValue;
			}
			set
			{
				this.guidValue = value;
				setChangedMember(ActionC.mbGuid);
			}
		}
		
		
		/// <summary>
		/// Action type.
		/// </summary>
		public EloixClient.IndexServer.feed.EActionType type
		{
			get
			{
				return typeValue;
			}
			set
			{
				this.typeValue = value;
			}
		}
		
		
		/// <summary>
		/// Feed GUID.
		/// </summary>
		/// <remarks>
		/// This action belongs to the feed identified by this GUID.
		/// </remarks>
		public String feedGuid
		{
			get
			{
				return feedGuidValue;
			}
			set
			{
				this.feedGuidValue = value;
				setChangedMember(ActionC.mbFeedGuid);
			}
		}
		
		
		/// <summary>
		/// Parent action GUID.
		/// </summary>
		/// <remarks>
		/// This element is only valid for user comments, {@link EActionType#UserComment}.
		/// If not empty, this action is subordinated under the action given by this GUID.
		/// </remarks>
		public String parentGuid
		{
			get
			{
				return parentGuidValue;
			}
			set
			{
				this.parentGuidValue = value;
				setChangedMember(ActionC.mbParentGuid);
			}
		}
		
		
		/// <summary>
		/// User GUID.
		/// </summary>
		/// <remarks>
		/// The GUID of the user who has created this action.
		/// For actions of type {@link EActionType#SordCreated}, this member holds the GUID of Sord.ownerId.
		/// For actions of type {@link EActionType#VersionCreated}, this member holds the GUID of DocVersion.ownerId.
		/// </remarks>
		public String userGuid
		{
			get
			{
				return userGuidValue;
			}
			set
			{
				this.userGuidValue = value;
				setChangedMember(ActionC.mbUserGuid);
			}
		}
		
		
		/// <summary>
		/// User ID.
		/// </summary>
		/// <remarks>
		/// It is set to the numerical ID of the user given by {@link #userGuid}.
		/// This element is read-only.
		/// </remarks>
		public int userId
		{
			get
			{
				return userIdValue;
			}
			set
			{
				this.userIdValue = value;
			}
		}
		
		
		/// <summary>
		/// User name.
		/// </summary>
		/// <remarks>
		/// It is set to the name of the user given by {@link #userGuid}.
		/// This element is read-only.
		/// </remarks>
		public String userName
		{
			get
			{
				return userNameValue;
			}
			set
			{
				this.userNameValue = value;
			}
		}
		
		
		/// <summary>
		/// Create date.
		/// </summary>
		/// <remarks>
		/// This element is the ISO formatted create date of the action.
		/// When this object is received from {@link FeedService#checkoutAction(de.elo.ix.client.ClientInfo, String, ActionZ)}
		/// or {@link FeedService#findFirstActions(de.elo.ix.client.ClientInfo, FindActionsInfo, int, ActionZ)} the value
		/// is supplied in the time zone of the client application - which is UTC by default.
		/// In case of the object is received by a notify message in {@link FeedNotification#updateAction(Action)} the
		/// value is relative to the UTC timezone.
		/// In order to convert this value into a date object, invoke function {@link de.elo.ix.client.IXConnection#isoToDate}.
		/// </remarks>
		public String createDateIso
		{
			get
			{
				return createDateIsoValue;
			}
			set
			{
				this.createDateIsoValue = value;
				setChangedMember(ActionC.mbCreateDateIso);
			}
		}
		
		
		/// <summary>
		/// Update date.
		/// </summary>
		/// <remarks>
		/// This element is only valid for {@link EActionType#UserComment}.
		/// It holds the ISO formatted update date.
		/// When this object is received from {@link FeedService#checkoutAction(de.elo.ix.client.ClientInfo, String, ActionZ)}
		/// or {@link FeedService#findFirstActions(de.elo.ix.client.ClientInfo, FindActionsInfo, int, ActionZ)} the value
		/// is supplied in the time zone of the client application - which is UTC by default.
		/// In case of the object is received by a notify message in {@link FeedNotification#updateAction(Action)} the
		/// value is relative to the UTC timezone.
		/// In order to convert this value into a date object, invoke function {@link de.elo.ix.client.IXConnection#isoToDate}.
		/// </remarks>
		public String updateDateIso
		{
			get
			{
				return updateDateIsoValue;
			}
			set
			{
				this.updateDateIsoValue = value;
				setChangedMember(ActionC.mbUpdateDateIso);
			}
		}
		
		
		/// <summary>
		/// Counts the number of updates.
		/// </summary>
		/// <remarks>
		/// This element is only valid for {@link EActionType#UserComment}.
		/// It counts the number of updates made to the comment.
		/// </remarks>
		public int changeCounter
		{
			get
			{
				return changeCounterValue;
			}
			set
			{
				this.changeCounterValue = value;
				setChangedMember(ActionC.mbChangeCounter);
			}
		}
		
		
		/// <summary>
		/// Comment text.
		/// </summary>
		/// <remarks>
		/// This element is only valid for {@link EActionType#UserComment},
		/// and {@link EActionType#AutoComment}.
		/// </remarks>
		public String text
		{
			get
			{
				return textValue;
			}
			set
			{
				this.textValue = value;
				setChangedMember(ActionC.mbText);
			}
		}
		
		
		/// <summary>
		/// GUID of the associated document version.
		/// </summary>
		/// <remarks>
		/// This element is only valid for generated actions that belong to a document version,
		/// e.g. {@link EActionType#VersionCreated}.
		/// Read-only.
		/// </remarks>
		public String docVersionGuid
		{
			get
			{
				return docVersionGuidValue;
			}
			set
			{
				this.docVersionGuidValue = value;
				setChangedMember(ActionC.mbDocVersionGuid);
			}
		}
		
		
		/// <summary>
		/// Document version object.
		/// </summary>
		/// <remarks>
		/// This element is only valid for generated actions that belong to a document version,
		/// e.g. {@link EActionType#VersionCreated}.
		/// Read-only.
		/// </remarks>
		public EloixClient.IndexServer.DocVersion docVersion
		{
			get
			{
				return docVersionValue;
			}
			set
			{
				this.docVersionValue = value;
				setChangedMember(ActionC.mbDocVersion);
			}
		}
		
		
		/// <summary>
		/// GUID of the associated workflow.
		/// </summary>
		/// <remarks>
		/// This element is valid for action types that belong to a workflow.
		/// </remarks>
		public String workflowGuid
		{
			get
			{
				return workflowGuidValue;
			}
			set
			{
				this.workflowGuidValue = value;
				setChangedMember(ActionC.mbWorkflowGuid);
			}
		}
		
		
		/// <summary>
		/// Workflow object.
		/// </summary>
		/// <remarks>
		/// This element is only valid for generated actions that belong to a workflow.
		/// Read-only.
		/// </remarks>
		public EloixClient.IndexServer.WFDiagram workflow
		{
			get
			{
				return workflowValue;
			}
			set
			{
				this.workflowValue = value;
				setChangedMember(ActionC.mbWorkflow);
			}
		}
		
		
		/// <summary>
		/// Time stamp.
		/// </summary>
		/// <remarks>
		/// Time stamp of creation or modification.
		/// </remarks>
		public String TStamp
		{
			get
			{
				return TStampValue;
			}
			set
			{
				this.TStampValue = value;
				setChangedMember(ActionC.mbTStamp);
			}
		}
		
		
		/// <summary>
		/// Change history of text member.
		/// </summary>
		/// <remarks>
		/// This list does not contain the current text.
		/// This member is null, if the text has not been changed.
		/// </remarks>
		public IList<EloixClient.IndexServer.feed.ActionHistory> history
		{
			get
			{
				return historyValue;
			}
			set
			{
				this.historyValue = value;
				setChangedMember(ActionC.mbHistory);
			}
		}
		
		
		/// <summary>
		/// Raw ACL representation.
		/// </summary>
		/// <remarks>
		/// Only valid for Actions of type {@link EActionType#UserComment} or {@link EActionType#AutoComment}.
		/// This member is ignored if {@link Action#aclItems} is not null.
		/// </remarks>
		public String acl
		{
			get
			{
				return aclValue;
			}
			set
			{
				this.aclValue = value;
				setChangedMember(ActionC.mbAcl);
			}
		}
		
		
		/// <summary>
		/// Access control list.
		/// </summary>
		/// <remarks>
		/// Only valid for Actions of type {@link EActionType#UserComment} or {@link EActionType#AutoComment}.
		/// This member has precedence before {@link Action#acl}.
		/// </remarks>
		public EloixClient.IndexServer.AclItem[] aclItems
		{
			get
			{
				return aclItemsValue;
			}
			set
			{
				this.aclItemsValue = value;
			}
		}
		
		
		/// <summary>
		/// Timestamp of this object's last export by the replication.
		/// </summary>
		public String TStampSync
		{
			get
			{
				return TStampSyncValue;
			}
			set
			{
				this.TStampSyncValue = value;
				setChangedMember(ActionC.mbTStampSync);
			}
		}
		
		
		#endregion
		
		#region Fields
		
		protected String guidValue;

		protected EloixClient.IndexServer.feed.EActionType typeValue;

		protected String feedGuidValue;

		protected String parentGuidValue;

		protected String userGuidValue;

		protected int userIdValue;

		protected String userNameValue;

		protected String createDateIsoValue;

		protected String updateDateIsoValue;

		protected int changeCounterValue;

		protected String textValue;

		protected String docVersionGuidValue;

		protected EloixClient.IndexServer.DocVersion docVersionValue;

		protected String workflowGuidValue;

		protected EloixClient.IndexServer.WFDiagram workflowValue;

		protected String TStampValue;

		protected IList<EloixClient.IndexServer.feed.ActionHistory> historyValue;

		protected String aclValue;

		protected EloixClient.IndexServer.AclItem[] aclItemsValue;

		protected String TStampSyncValue;

		#endregion
		
		
		public static readonly new long serialVersionUID = 736351635L;		
	} // end class
}  // end namespace
