//
// 
// THIS FILE HAS BEEN GENERATED. DO NOT MODIFY.
//

using System;
using System.Collections.Generic;
using byps;

namespace EloixClient.IndexServer.feed
{
	
	/// <summary>
	/// This class represents a document feed.
	/// </summary>
	/// <remarks>
	/// Each Sord can have at most one Feed object. A Feed contains of a list of Action objects which can be user comments,
	/// comments generated by scripts and actions generated by the system.
	/// The Feed object acts like a header for the list of actions. Its main purpose is the mapping between feed actions and a Sord object.
	/// In order to receive a feed of a Sord object inclusive all actions, call function {@link FeedService#findFirstActions(de.elo.ix.client.ClientInfo, FindActionsInfo, int, ActionZ)}.
	/// </remarks>
	public class Feed : EloixClient.IndexServer.ValueClass, BSerializable
	{
	
		#region Constructors
		
		public Feed() {
		}		
		
		public Feed(String @guid, String @createDateIso, String @tStamp, String @objGuid, String @TStampSync) {
			this.guidValue = @guid;
			this.createDateIsoValue = @createDateIso;
			this.tStampValue = @tStamp;
			this.objGuidValue = @objGuid;
			this.TStampSyncValue = @TStampSync;
		}		
		
		public Feed(Feed rhs) : base(rhs)
		{
			this.guidValue = rhs.guidValue;
			this.createDateIsoValue = rhs.createDateIsoValue;
			this.tStampValue = rhs.tStampValue;
			this.objGuidValue = rhs.objGuidValue;
			this.TStampSyncValue = rhs.TStampSyncValue;
		}		
		
		#endregion
		
		#region Properties
		
		/// <summary>
		/// Feed GUID.
		/// </summary>
		public String guid
		{
			get
			{
				return guidValue;
			}
			set
			{
				this.guidValue = value;
				setChangedMember(FeedC.mbGuid);
			}
		}
		
		
		/// <summary>
		/// Create date.
		/// </summary>
		/// <remarks>
		/// It holds the ISO formatted create date in the time zone of the client application.
		/// In order to convert this value into a date object, invoke function {@link de.elo.ix.client.IXConnection#isoToDate}.
		/// </remarks>
		public String createDateIso
		{
			get
			{
				return createDateIsoValue;
			}
			set
			{
				this.createDateIsoValue = value;
				setChangedMember(FeedC.mbCreateDateIso);
			}
		}
		
		
		/// <summary>
		/// Time stamp.
		/// </summary>
		/// <remarks>
		/// Time stamp of creation or modification.
		/// </remarks>
		public String tStamp
		{
			get
			{
				return tStampValue;
			}
			set
			{
				this.tStampValue = value;
				setChangedMember(FeedC.mbTStamp);
			}
		}
		
		
		/// <summary>
		/// GUID of the associated Sord object.
		/// </summary>
		public String objGuid
		{
			get
			{
				return objGuidValue;
			}
			set
			{
				this.objGuidValue = value;
				setChangedMember(FeedC.mbObjGuid);
			}
		}
		
		
		/// <summary>
		/// Timestamp of this object's last export by the replication.
		/// </summary>
		public String TStampSync
		{
			get
			{
				return TStampSyncValue;
			}
			set
			{
				this.TStampSyncValue = value;
				setChangedMember(FeedC.mbTStampSync);
			}
		}
		
		
		#endregion
		
		#region Fields
		
		protected String guidValue;

		protected String createDateIsoValue;

		protected String tStampValue;

		protected String objGuidValue;

		protected String TStampSyncValue;

		#endregion
		
		
		public static readonly new long serialVersionUID = 556531185L;		
	} // end class
}  // end namespace
