//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EloixClientUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EloixClientUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Dokumente ähnelt.
        /// </summary>
        public static string AllDocuments {
            get {
                return ResourceManager.GetString("AllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Notizen ähnelt.
        /// </summary>
        public static string AllNotes {
            get {
                return ResourceManager.GetString("AllNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Ordner ähnelt.
        /// </summary>
        public static string AllStructures {
            get {
                return ResourceManager.GetString("AllStructures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle ähnelt.
        /// </summary>
        public static string AllTypes {
            get {
                return ResourceManager.GetString("AllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Archive Path ähnelt.
        /// </summary>
        public static string ArcPath {
            get {
                return ResourceManager.GetString("ArcPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string BtnOK {
            get {
                return ResourceManager.GetString("BtnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add to the fulltext ähnelt.
        /// </summary>
        public static string CheckBox_AddToFulltext_Text {
            get {
                return ResourceManager.GetString("CheckBox.AddToFulltext.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CloseButtonX {
            get {
                object obj = ResourceManager.GetObject("CloseButtonX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Created by ähnelt.
        /// </summary>
        public static string CreateBy {
            get {
                return ResourceManager.GetString("CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Date ähnelt.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keywording Form ähnelt.
        /// </summary>
        public static string DocMask {
            get {
                return ResourceManager.GetString("DocMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string DocumentDate {
            get {
                return ResourceManager.GetString("DocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Dokument ist verschlüsselt.
        ///Bitte geben Sie das Passwort für den Schlüsselkreis {0} ein. ähnelt.
        /// </summary>
        public static string EncryptedDocumentInstructionLabel_Text {
            get {
                return ResourceManager.GetString("EncryptedDocumentInstructionLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verschlüsseltes Dokument ähnelt.
        /// </summary>
        public static string EncryptionDlg_EncryptedDoc {
            get {
                return ResourceManager.GetString("EncryptionDlg_EncryptedDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie das Passwort ein. ähnelt.
        /// </summary>
        public static string EncryptionDlg_PleasePutInPswd {
            get {
                return ResourceManager.GetString("EncryptionDlg_PleasePutInPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verschlüsselungspasswort ähnelt.
        /// </summary>
        public static string EncryptionPassword {
            get {
                return ResourceManager.GetString("EncryptionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Ändern der Verschlagwortungsmaske ist nicht richtig erfolgt.EditInfo ist null. ähnelt.
        /// </summary>
        public static string Error_Indexing_ChangeDocMask_EditInfoNull {
            get {
                return ResourceManager.GetString("Error.Indexing.ChangeDocMask.EditInfoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Entfernen der der Verschlagwortungscontrols ist ein Fehler aufgetreten. ähnelt.
        /// </summary>
        public static string Error_Indexing_ClearView_Message {
            get {
                return ResourceManager.GetString("Error.Indexing.ClearView.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim erzeugen des Items für den Sordtyp ist ein Fehler aufgetreten. ähnelt.
        /// </summary>
        public static string Error_Indexing_CreatingItemForSordType_Message {
            get {
                return ResourceManager.GetString("Error.Indexing.CreatingItemForSordType.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Liste der Verschlagwortungsmasken konnten nicht angezeigt werden, da die Verbindung zum Indexserver nicht vorhanden ist ähnelt.
        /// </summary>
        public static string Error_Indexing_DocMasks_NoConnection {
            get {
                return ResourceManager.GetString("Error.Indexing.DocMasks.NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Verschlagwortungsmaske kann nicht angezeigt werden. Die Referenz auf sord ist null. ähnelt.
        /// </summary>
        public static string Error_Indexing_DocMaskView_SordNull {
            get {
                return ResourceManager.GetString("Error.Indexing.DocMaskView.SordNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Verschlagwortungsmaske des Sordobjekts konnten nicht aus dem DockMaskCache ermittelt werden. ähnelt.
        /// </summary>
        public static string Error_Indexing_GettingDocMaskFromCache_Message {
            get {
                return ResourceManager.GetString("Error.Indexing.GettingDocMaskFromCache.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Eingabefelder der Verschlagwortungsmaske konnten nicht angezeigt werden. Die Referenz auf docMask is null. ähnelt.
        /// </summary>
        public static string Error_Indexing_IndexingFields_DocMaskNull {
            get {
                return ResourceManager.GetString("Error.Indexing.IndexingFields.DocMaskNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Laden des Bildes für den Objekttyp. ähnelt.
        /// </summary>
        public static string Error_Indexing_LoadImageForObjectType {
            get {
                return ResourceManager.GetString("Error.Indexing.LoadImageForObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Laden der Suchmodustypen ist ein Fehler aufgetreten. ähnelt.
        /// </summary>
        public static string Error_Indexing_LoadingModeTypes_Message {
            get {
                return ResourceManager.GetString("Error.Indexing.LoadingModeTypes.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Laden der Notizentypen, nach denen gesucht werden kann, ist ein Fehler aufgetreten. ähnelt.
        /// </summary>
        public static string Error_Indexing_LoadingNotesTypes_Message {
            get {
                return ResourceManager.GetString("Error.Indexing.LoadingNotesTypes.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Laden der ObjKeys für die Suche, ist ein Fehler aufgetreten. ähnelt.
        /// </summary>
        public static string Error_Indexing_LoadingObjKeyData_Message {
            get {
                return ResourceManager.GetString("Error.Indexing.LoadingObjKeyData.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler bei Auswahl der Verschlagwortungsmaske. ähnelt.
        /// </summary>
        public static string Error_Indexing_SelectDocMask {
            get {
                return ResourceManager.GetString("Error.Indexing.SelectDocMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei der Auswahl des Benutzer für die Suchoption \&quot;Abgelegt von\&quot;, ist ein Fehler aufgetreten. ähnelt.
        /// </summary>
        public static string Error_Indexing_SelectingUser_Message {
            get {
                return ResourceManager.GetString("Error.Indexing.SelectingUser.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Setzen der Werte der Verschlagwortungsmaske ist ein Fehler aufgetreten. ähnelt.
        /// </summary>
        public static string Error_Indexing_SetDocMaskValues {
            get {
                return ResourceManager.GetString("Error.Indexing.SetDocMaskValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Setzen von ISO Datum ähnelt.
        /// </summary>
        public static string Error_Indexing_SetISODate {
            get {
                return ResourceManager.GetString("Error.Indexing.SetISODate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Setzen des Objekttyps. ähnelt.
        /// </summary>
        public static string Error_Indexing_SetObjectType {
            get {
                return ResourceManager.GetString("Error.Indexing.SetObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Setzen der default Verschlagwortungsmaske für die Suche ist ein Fehler aufgetreten. ähnelt.
        /// </summary>
        public static string Error_Indexing_SettingDefaultDocMaskForSearch_Message {
            get {
                return ResourceManager.GetString("Error.Indexing.SettingDefaultDocMaskForSearch.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Setzen der Verschlagwortungsmaske in Form von ObjKeys in dem Sord objekt, ist ein Fehler aufgetreten. ähnelt.
        /// </summary>
        public static string Error_Indexing_SettingDocMaskInSord_Message {
            get {
                return ResourceManager.GetString("Error.Indexing.SettingDocMaskInSord.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Feld Kurzbezeichnung muss mindestens ein Zeichen enthalten
        ///und darf nicht mit einem Leerzeichen oder einem &apos;.&apos; beginnen. ähnelt.
        /// </summary>
        public static string Error_Indexing_ShortDescription_BelowMinLength {
            get {
                return ResourceManager.GetString("Error.Indexing.ShortDescription.BelowMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Behandlung des Events &apos;TextChanged&apos; hat einen Fehler verursacht. ähnelt.
        /// </summary>
        public static string Error_Indexing_TextChanged {
            get {
                return ResourceManager.GetString("Error.Indexing.TextChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Übernehmen der Änderungen aus der Verschlagwortungsmaske ist ein Fehler aufgetreten. ähnelt.
        /// </summary>
        public static string Error_Indexing_TransferDocMaskChanges {
            get {
                return ResourceManager.GetString("Error.Indexing.TransferDocMaskChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aufgrund eines unerwarteten Fehlers kann die Verschlagwortungsmaske nicht angezeigt werden. ähnelt.
        /// </summary>
        public static string Error_Indexing_UnknownError_DocMaskView {
            get {
                return ResourceManager.GetString("Error.Indexing.UnknownError.DocMaskView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aufgrund eines unbekannten Fehlers, können nicht alle Indexfelder der Maske angezeigt werden. ähnelt.
        /// </summary>
        public static string Error_Indexing_UnknownError_IndexingFields {
            get {
                return ResourceManager.GetString("Error.Indexing.UnknownError.IndexingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei Durchführung der Verschlagwortung trat ein unerwateter Fehler auf. ähnelt.
        /// </summary>
        public static string Error_Indexing_UnknownError_Process {
            get {
                return ResourceManager.GetString("Error.Indexing.UnknownError.Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unerwarteter Fehler ist beim Setzen der Verschlagwortungsmaske augetreten. ähnelt.
        /// </summary>
        public static string Error_Indexing_UnknownError_SetDocMask {
            get {
                return ResourceManager.GetString("Error.Indexing.UnknownError.SetDocMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Anzeigen der Verschlagwortung für einen ausgewählten Ordner/Dokument. ähnelt.
        /// </summary>
        public static string Error_Indexing_View {
            get {
                return ResourceManager.GetString("Error.Indexing.View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximale Länge beträgt {0} Zeichen. ähnelt.
        /// </summary>
        public static string Error_MaxLength {
            get {
                return ResourceManager.GetString("Error.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimale Länge beträgt {0} Zeichen. ähnelt.
        /// </summary>
        public static string Error_MinLength {
            get {
                return ResourceManager.GetString("Error.MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Passwörter stimmen nicht überein! ähnelt.
        /// </summary>
        public static string Error_PasswordMismatch {
            get {
                return ResourceManager.GetString("Error.PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Fehler ist bei der Auswahl des SordTyps aufgetreten. ähnelt.
        /// </summary>
        public static string Error_SelectSordType {
            get {
                return ResourceManager.GetString("Error.SelectSordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Erstellen des Controls KeywordTextBox tratt ein unerwarteter Fehler auf. ähnelt.
        /// </summary>
        public static string Exception_Indexing_CreateKeywordTextBox_Message {
            get {
                return ResourceManager.GetString("Exception.Indexing.CreateKeywordTextBox.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde eine Referenz auf null für DocMaskLine an die Methode GetIndexFieldControl übergeben. ähnelt.
        /// </summary>
        public static string Exception_Indexing_GetIndexFieldControlNullRef_Message {
            get {
                return ResourceManager.GetString("Exception.Indexing.GetIndexFieldControlNullRef.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Laden der Liste der Verschlagwortungsmasken ist ein Fehler aufgetreten. ähnelt.
        /// </summary>
        public static string Exception_Indexing_LoadDocMasks_Message {
            get {
                return ResourceManager.GetString("Exception.Indexing.LoadDocMasks.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbindung zum Indexserver oder Referenz zum TableLayoutPanel sind null ähnelt.
        /// </summary>
        public static string Exception_Indexing_NoConnectionOrPanelRef_Message {
            get {
                return ResourceManager.GetString("Exception.Indexing.NoConnectionOrPanelRef.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Anzahl der Nachkommastellen muss größer 0 sein. ähnelt.
        /// </summary>
        public static string Exception_Indexing_RegEx_Fraction {
            get {
                return ResourceManager.GetString("Exception.Indexing.RegEx.Fraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler. MinCharLength/MaxCharLength müssen größer sein. MaxCharLength muss größer sein als MinCharLength. ähnelt.
        /// </summary>
        public static string Exception_Indexing_RegEx_MinMaxChar_Message {
            get {
                return ResourceManager.GetString("Exception.Indexing.RegEx.MinMaxChar.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde eine Referenz auf Null für docMask an die Methode SetNewDockMask übergeben ähnelt.
        /// </summary>
        public static string Exception_Indexing_SetNewDocMaskNullRef_Message {
            get {
                return ResourceManager.GetString("Exception.Indexing.SetNewDocMaskNullRef.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum &quot;Von&quot; darf nicht größer sein als Datum &quot;Bis&quot; ähnelt.
        /// </summary>
        public static string Exception_Search_DateFromGreaterDateUntil_Message {
            get {
                return ResourceManager.GetString("Exception.Search.DateFromGreaterDateUntil.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum &quot;Bis&quot; darf nicht kleiner sein als Datum &quot;Von&quot; ähnelt.
        /// </summary>
        public static string Exception_Search_DateUntilGreaterDateFrom_Message {
            get {
                return ResourceManager.GetString("Exception.Search.DateUntilGreaterDateFrom.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fctIconDelete {
            get {
                object obj = ResourceManager.GetObject("fctIconDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filing Date ähnelt.
        /// </summary>
        public static string FilingDate {
            get {
                return ResourceManager.GetString("FilingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Keyword ähnelt.
        /// </summary>
        public static string FormKeywordList {
            get {
                return ResourceManager.GetString("FormKeywordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Users and Groups ähnelt.
        /// </summary>
        public static string FormSelectUserCaption {
            get {
                return ResourceManager.GetString("FormSelectUserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string FormSelectUserSearch {
            get {
                return ResourceManager.GetString("FormSelectUserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemeine Haftnotiz ähnelt.
        /// </summary>
        public static string GeneralNotes {
            get {
                return ResourceManager.GetString("GeneralNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group ähnelt.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Groups ähnelt.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID ähnelt.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImgGroup {
            get {
                object obj = ResourceManager.GetObject("ImgGroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImgGroupDisabled {
            get {
                object obj = ResourceManager.GetObject("ImgGroupDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImgUser {
            get {
                object obj = ResourceManager.GetObject("ImgUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImgUserDisabled {
            get {
                object obj = ResourceManager.GetObject("ImgUserDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ELO Info ähnelt.
        /// </summary>
        public static string InfoMessage_Title {
            get {
                return ResourceManager.GetString("InfoMessage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input ähnelt.
        /// </summary>
        public static string InputBoxCaption {
            get {
                return ResourceManager.GetString("InputBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keyword already exists ähnelt.
        /// </summary>
        public static string KeywordAlreadyExists {
            get {
                return ResourceManager.GetString("KeywordAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lock ID ähnelt.
        /// </summary>
        public static string LockId {
            get {
                return ResourceManager.GetString("LockId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Locked By ähnelt.
        /// </summary>
        public static string LockName {
            get {
                return ResourceManager.GetString("LockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        public static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: {0} ähnelt.
        /// </summary>
        public static string Message_ExceptionErrorMessage {
            get {
                return ResourceManager.GetString("Message.ExceptionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die aktuelle Verschlagwortungsmaske enthält
        ///Indexfelder, die in der neu gewählten Maske
        ///vorhanden sind. Die eingegebenen Daten in diesen
        ///Zeilen werden beim Maskenwechsel gelöscht.
        ///
        ///Wollen Sie auf die neue Maske wechseln? ähnelt.
        /// </summary>
        public static string Message_Indexing_ChangeDocMask {
            get {
                return ResourceManager.GetString("Message.Indexing.ChangeDocMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie haben nicht das Recht zur Änderung der Verschlagwortungsmaske. ähnelt.
        /// </summary>
        public static string Message_Indexing_ChangeDocMask_InsufficentRights {
            get {
                return ResourceManager.GetString("Message.Indexing.ChangeDocMask.InsufficentRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei der Auswahl des Schlüssels ist ein Fehler aufgetreten.
        ///Mögliche Ursachen:
        ///Es wurde kein für das Indexfeld gültiger Schlüssel ausgewählt. ähnelt.
        /// </summary>
        public static string Message_Indexing_KeySelectionError {
            get {
                return ResourceManager.GetString("Message.Indexing.KeySelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Übernehmen der Änderungen aus der Verschlagwortungsmaske, ist ein Fehler aufgetreten.
        ///Die vorgenommenen Änderungen werden nicht übernommen. ähnelt.
        /// </summary>
        public static string Message_Indexing_TransferDocMaskChangesError {
            get {
                return ResourceManager.GetString("Message.Indexing.TransferDocMaskChangesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verschlagwortung nicht durchführbar, da kein Dokument
        ///ausgewählt wurde oder die Verbindung zum Indexserver nicht vorhanden ist. ähnelt.
        /// </summary>
        public static string Message_Indexing_UnableToProcess_NoConnectionOrNoDoc {
            get {
                return ResourceManager.GetString("Message.Indexing.UnableToProcess.NoConnectionOrNoDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In das Indexfeld können nur Dezimalzahlen mit einer Nachkommastelle eingegeben werden. ähnelt.
        /// </summary>
        public static string Message_Indexing_Validation_DoubleF1Field {
            get {
                return ResourceManager.GetString("Message.Indexing.Validation.DoubleF1Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In das Indexfeld können nur Dezimalzahlen mit {0} Nachkommastellen eingegeben werden. ähnelt.
        /// </summary>
        public static string Message_Indexing_Validation_DoubleFxField {
            get {
                return ResourceManager.GetString("Message.Indexing.Validation.DoubleFxField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In das Indexfeld können nur ganze Zahlen eingegeben werden. ähnelt.
        /// </summary>
        public static string Message_Indexing_Validation_IntegerField {
            get {
                return ResourceManager.GetString("Message.Indexing.Validation.IntegerField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Eingabe ist zu lang. Sie kann maximal {0} Zeichen enthalten. Momentane Textlänge: {1} ähnelt.
        /// </summary>
        public static string Message_Indexing_Validation_MaxLengthFailure {
            get {
                return ResourceManager.GetString("Message.Indexing.Validation.MaxLengthFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Eingabe ist zu kurz. Sie muss mindestens {0} Zeichen enthalten. Momentane Textlänge: {1} ähnelt.
        /// </summary>
        public static string Message_Indexing_Validation_MinLengthFailure {
            get {
                return ResourceManager.GetString("Message.Indexing.Validation.MinLengthFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Verschlagwortung kann nicht abgeschlossen werden,
        ///da Sie nicht alle Indexfelder richtig ausgefüllt haben. ähnelt.
        /// </summary>
        public static string Message_InvalidIndexingFields_Text {
            get {
                return ResourceManager.GetString("Message.InvalidIndexingFields.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die erweiterte Suche kann nicht abgeschlossen werden,
        ///da Sie nicht alle Indexfelder richtig ausgefüllt haben. ähnelt.
        /// </summary>
        public static string Message_Search_InputInvalid {
            get {
                return ResourceManager.GetString("Message.Search.InputInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm ähnelt.
        /// </summary>
        public static string MsgBoxConfirm {
            get {
                return ResourceManager.GetString("MsgBoxConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Folder ähnelt.
        /// </summary>
        public static string NewFolderName {
            get {
                return ResourceManager.GetString("NewFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Keyword ähnelt.
        /// </summary>
        public static string NewKeyword {
            get {
                return ResourceManager.GetString("NewKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die four ähnelt.
        /// </summary>
        public static string Numbers_Four {
            get {
                return ResourceManager.GetString("Numbers.Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die six ähnelt.
        /// </summary>
        public static string Numbers_Six {
            get {
                return ResourceManager.GetString("Numbers.Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die two ähnelt.
        /// </summary>
        public static string Numbers_Two {
            get {
                return ResourceManager.GetString("Numbers.Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Owner ähnelt.
        /// </summary>
        public static string Onwer {
            get {
                return ResourceManager.GetString("Onwer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OutlookBlueButton {
            get {
                object obj = ResourceManager.GetObject("OutlookBlueButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OutlookOrangeButton {
            get {
                object obj = ResourceManager.GetObject("OutlookOrangeButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ähnelt.
        /// </summary>
        public static string Password1_Label {
            get {
                return ResourceManager.GetString("Password1.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort (Wiederholung) ähnelt.
        /// </summary>
        public static string Password2_Label {
            get {
                return ResourceManager.GetString("Password2.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Persönliche Haftnotiz ähnelt.
        /// </summary>
        public static string PersonalNotes {
            get {
                return ResourceManager.GetString("PersonalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Priority ähnelt.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die High ähnelt.
        /// </summary>
        public static string PriorityHigh {
            get {
                return ResourceManager.GetString("PriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Low ähnelt.
        /// </summary>
        public static string PriorityLow {
            get {
                return ResourceManager.GetString("PriorityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medium ähnelt.
        /// </summary>
        public static string PriorityMedium {
            get {
                return ResourceManager.GetString("PriorityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure to delete this item? ähnelt.
        /// </summary>
        public static string QueryDelete {
            get {
                return ResourceManager.GetString("QueryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete this item and all subitems? ähnelt.
        /// </summary>
        public static string QueryDeleteItemAndAllSubItems {
            get {
                return ResourceManager.GetString("QueryDeleteItemAndAllSubItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have modified the keyword list. Do you want to save the changes? ähnelt.
        /// </summary>
        public static string QuerySaveModifiedKeywordList {
            get {
                return ResourceManager.GetString("QuerySaveModifiedKeywordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abgelegt von ... ähnelt.
        /// </summary>
        public static string SavedBy {
            get {
                return ResourceManager.GetString("SavedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suche ähnelt.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AND (Felder mit boolschem UND verknüpfen) ähnelt.
        /// </summary>
        public static string SearchOption_ModeType_AND {
            get {
                return ResourceManager.GetString("SearchOption.ModeType.AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OR (Felder mit boolschem OR verknüpfen) ähnelt.
        /// </summary>
        public static string SearchOption_ModeType_OR {
            get {
                return ResourceManager.GetString("SearchOption.ModeType.OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size ähnelt.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stempel ähnelt.
        /// </summary>
        public static string Stamps {
            get {
                return ResourceManager.GetString("Stamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string TaskDate {
            get {
                return ResourceManager.GetString("TaskDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Memo ähnelt.
        /// </summary>
        public static string TaskMemo {
            get {
                return ResourceManager.GetString("TaskMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task ähnelt.
        /// </summary>
        public static string TaskType {
            get {
                return ResourceManager.GetString("TaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activity ähnelt.
        /// </summary>
        public static string TaskTypeActivity {
            get {
                return ResourceManager.GetString("TaskTypeActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder ähnelt.
        /// </summary>
        public static string TaskTypeReminder {
            get {
                return ResourceManager.GetString("TaskTypeReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workflow ähnelt.
        /// </summary>
        public static string TaskTypeWorkflow {
            get {
                return ResourceManager.GetString("TaskTypeWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Users ähnelt.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
